# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161027_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='media',
        ),
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.FileField(blank=True, null=True, upload_to='scores'),
        ),
    ]
