# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20161027_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='category',
            field=models.CharField(default='sound', max_length=30, null=True),
        ),
    ]
