# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20161108_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linktype',
            field=models.CharField(blank=True, default='score', max_length=20, null=True),
        ),
    ]
