# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_linktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
